# Generated by Django 3.1.3 on 2020-12-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('task', models.CharField(max_length=1500)),
                ('status', models.BooleanField()),
                ('priority', models.CharField(max_length=30)),
                ('initial_date', models.DateField()),
                ('limit_date', models.DateField()),
                ('author_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usertoken')),
            ],
        ),
    ]
