# Generated by Django 3.1 on 2020-12-10 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_accomplishment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='accomplishment_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 10, 13, 47, 43, 905750, tzinfo=utc)),
        ),
    ]
